services:
  postgres:
    image: postgres:15
    container_name: postgres_container_client
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin     
      POSTGRES_PASSWORD: mystrongpassword
      POSTGRES_DB: client_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
